# Generated by Django 5.1.4 on 2025-10-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_history', '0003_clinicalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldocument',
            name='file',
            field=models.FileField(storage='apps.clinical_history.storage.ClinicalDocumentS3Storage', upload_to='clinical_documents/%Y/%m/%d/'),
        ),
    ]
