# Generated by Django 5.1.4 on 2025-11-02 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_history', '0004_alter_clinicaldocument_file'),
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialTriage',
            fields=[
                ('patient', models.OneToOneField(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='initial_triage', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('answers', models.JSONField(default=dict, help_text='JSON con las preguntas y respuestas del árbol de triaje.')),
                ('pre_diagnosis', models.CharField(blank=True, help_text='Diagnóstico preliminar basado en el triaje.', max_length=255)),
                ('recommendation', models.TextField(blank=True, help_text='Recomendación generada por el sistema.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Triaje Inicial',
                'verbose_name_plural': 'Triajes Iniciales',
            },
        ),
    ]
