# Generated by Django 5.1.4 on 2025-11-02 22:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_history', '0005_initialtriage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('mood', models.CharField(choices=[('feliz', 'Feliz'), ('triste', 'Triste'), ('ansioso', 'Ansioso/a'), ('enojado', 'Enojado/a'), ('neutral', 'Neutral'), ('cansado', 'Cansado/a')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el estado de ánimo.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='mood_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Ánimo',
                'verbose_name_plural': 'Diario de Ánimos',
                'ordering': ['-date'],
                'unique_together': {('patient', 'date')},
            },
        ),
    ]
