# Generated by Django 5.1.4 on 2025-11-04 00:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_referral'),
        ('clinical_history', '0006_moodjournal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='appointments.appointment')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to=settings.AUTH_USER_MODEL)),
                ('psychologist', models.ForeignKey(limit_choices_to={'user_type': 'professional'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_objectives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objetivo Terapéutico',
                'verbose_name_plural': 'Objetivos Terapéuticos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('recurrence', models.CharField(choices=[('once', 'Una vez'), ('daily', 'Diaria'), ('weekly', 'Semanal')], default='daily', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='clinical_history.objective')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, help_text='Notas opcionales del paciente.', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='clinical_history.task')),
            ],
            options={
                'verbose_name': 'Tarea Completada',
                'verbose_name_plural': 'Tareas Completadas',
                'ordering': ['-completed_date'],
                'unique_together': {('task', 'patient', 'completed_date')},
            },
        ),
    ]
