# Generated by Django 5.1.4 on 2025-11-05 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_history', '0007_objective_task_taskcompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(help_text='Nombre del medicamento', max_length=255)),
                ('dosage', models.CharField(help_text='Dosis (ej: 10mg, 1 comprimido)', max_length=100)),
                ('frequency', models.CharField(help_text="Frecuencia (ej: '1 vez al día por la noche')", max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Instrucciones adicionales o notas')),
                ('is_active', models.BooleanField(default=True, help_text='Marcar como inactivo si el tratamiento finalizó')),
                ('prescribed_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, help_text='Fecha de finalización del tratamiento (opcional)', null=True)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('psychiatrist', models.ForeignKey(limit_choices_to={'user_type': 'professional'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receta (Tratamiento)',
                'verbose_name_plural': 'Recetas (Tratamientos)',
                'ordering': ['-prescribed_date'],
            },
        ),
    ]
