# Generated by Django on 2025-11-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical_history', '0008_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='Hora del recordatorio (ej: 08:00, 20:00)')),
                ('days_of_week', models.JSONField(default=list, help_text='Lista de días: [1,2,3,4,5] para L-V, [0,1,2,3,4,5,6] para todos')),
                ('is_active', models.BooleanField(default=True)),
                ('send_notification', models.BooleanField(default=True, help_text='Enviar notificación push')),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='clinical_history.prescription')),
            ],
            options={
                'verbose_name': 'Recordatorio de Medicamento',
                'verbose_name_plural': 'Recordatorios de Medicamentos',
                'db_table': 'medication_reminders',
                'ordering': ['time'],
            },
        ),
    ]
