# Generated by Django 5.1.4 on 2025-11-05 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_referral'),
        ('payment_system', '0002_patientplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transaction', to='appointments.appointment'),
        ),
    ]
