# Generated by Django 5.1.4 on 2025-11-04 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_publicuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinic_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Porcentaje de comisión que la clínica cobra por cada pago.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
