# Generated by Django 5.1.4 on 2025-11-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_clinic_clinic_fee_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='backup_schedule',
            field=models.CharField(choices=[('disabled', 'Desactivado'), ('daily', 'Diario'), ('weekly', 'Semanal')], default='disabled', help_text='Frecuencia de los backups automáticos.', max_length=10),
        ),
        migrations.AddField(
            model_name='clinic',
            name='last_backup_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del último backup automático.', null=True),
        ),
    ]
