# Generated by Django 5.1.4 on 2025-11-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_clinic_backup_schedule_clinic_last_backup_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='next_scheduled_backup',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora exacta programada para el próximo backup.', null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='backup_schedule',
            field=models.CharField(choices=[('disabled', 'Desactivado'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('scheduled', 'Programado por Fecha')], default='disabled', help_text='Frecuencia de los backups automáticos.', max_length=10),
        ),
    ]
