# Generated by Django 5.1.4 on 2025-11-02 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_psychologist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Motivo de la derivación.')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='appointments.appointment')),
                ('referred_psychologist', models.ForeignKey(limit_choices_to={'user_type': 'professional'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referring_psychologist', models.ForeignKey(limit_choices_to={'user_type': 'professional'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Derivación',
                'verbose_name_plural': 'Derivaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
