# Generated by Django 5.1.4 on 2025-11-05 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_referral'),
        ('payment_system', '0003_alter_paymenttransaction_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_plan',
            field=models.ForeignKey(blank=True, help_text='Plan del paciente utilizado para esta cita (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_used', to='payment_system.patientplan'),
        ),
    ]
