# Generated by Django 5.1.4 on 2025-11-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='fcm_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='platform',
            field=models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
